# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c95e0f557ff87e85bcd1d9b50fd74262edf10622f25063140dbb0aff6fbdad9def0927e4bcc39fa37c39a074a45cd4336984fe656f81119d4b0839cf9ebd5c2

test:
  secret_key_base: 734d655a4bda9f05dd0090f34af23587c9c3b7eae2e0da7bcf595df632a36911eb46dbfbbc3b5e77027347d78f45d574d290a6c2badb9d4ee4558eaf914640be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
